### ISSUE TITLE
Add sphinx docs

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo-client#10]

**Comment by scarrazza** [comment]
@marcorossi5 could you please enable the docs workflow so it can render the documentation online?

**Comment by marcorossi5** [comment]
Is the docs workflow to be run manually, right?

**Comment by scarrazza** [comment]
Not really, we want to execute automatically when code is merged on the main folder (so this will generate the latest documentation) and when releasing the package. Please use the same workflow available in qibo/qibojit/qibolab/qibocal.
