### ISSUE TITLE
Rename package and project

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo-client#11]
Given that we are planning to support multiple providers, I think we should rename this package in `qibo-providers` and just mention the names of the providers in the documentation (at the moment TIIProvider).

**Comment by scarrazza** [comment]
@marcorossi5, I have already changed the github name.

**Comment by scarrazza** [comment]
@marcorossi5, thinking more about this, could you please perform the following changes:
- rename this project as `qibo-client`
- create an abstract `Client` class, which should takes the web service url and token.
- rename the `TIIProvider` class in a `def TII(token):` function which should return the allocated `Client(tii_url, token)`

I believe this change is good because we are planning to have another family of [cloud backends](https://github.com/qiboteam/qibo-cloud-backends) directly integrated in Qibo's set/get backend mechanism, therefore this client can be integrated easily with that system, and furthermore it is not really needed to create special providers for different labs using a similar approach to TII.

**Comment by marcorossi5** [comment]
Yes, it seems clean. I'll code this in a couple of days.
