### ISSUE TITLE
Raise warning instead of error if Qibo version doesn't match the lab

### ISSUE THREAD

**Issue by MatteoRobbiati** [qiboteam/qibo-client#24]
This is just to discuss if we want to keep the error (and the breakout) if the Qibo's versions don't match.
In my case Qibo in devmode (0.2.5) breaks the execution.
This issue is raised after a discussion had with @BrunoLiegiBastonLiegi.

**Comment by BrunoLiegiBastonLiegi** [comment]
Yes, personally I believe it might be enough to raise a warning or to raise the error only if the version is older than some `qibo` release we know to have significantly changed it.
