### ISSUE TITLE
`JSONDecodeError` when callin `run_circuit`

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [qiboteam/qibo-client#66]
Some `qibo-cloud-backends` tests are failing due to `qibo-client` qiboteam/qibo-cloud-backends#37.
I am using `qibo-client 0.0.9` and running a circuit raises `JSONDecodeError: Expecting value: line 2 column 1 (char 1)`.
The example in the README fails for instance.

**Comment by scarrazza** [comment]
I confirm, @marcorossi5 could you please have a look asap?

**Comment by marcorossi5** [comment]
Yes, he is not using the latest qibo-client version. We have not released it yet (`0.0.10`). Let me check everything is working and we can make the release. Can you confirm that the qibo version you just released is `0.2.12`?

**Comment by scarrazza** [comment]
I have just tried in PR https://github.com/qiboteam/qibo-client/pull/65 but it does not work too, same error.

**Comment by marcorossi5** [comment]
The former example was:

```python
import qibo
from qibo_client import Client

circuit = qibo.models.QFT(5)
token_path = Path(__file__).parent / "token.txt"
token = token_path.read_text()
client = Client(token)
job = client.run_circuit(circuit, nshots=100, device="sim")

r = job.result(verbose=True)
print(r.frequencies())
```
We should replace by this working example

```python
import qibo
from qibo_client import Client

circuit = qibo.Circuit(5)
circuit.add(qibo.gates.M(0))

token_path = Path(__file__).parent / "token.txt"
token = token_path.read_text()
client = Client(token)
job = client.run_circuit(circuit, nshots=100, device="sim")

r = job.result(verbose=True)
print(r.frequencies())
```
Any idea on why `models.QFT` is not working?

**Comment by scarrazza** [comment]
In principle we should be able to support circuit simulations without measurement gates (for sim partitions) and with measurement gates for hardware partitions.

**Comment by scarrazza** [comment]
As discussed, if you don't add the M gate, you should not expect samples/frequencies but just the state vector.

**Comment by scarrazza** [comment]
I have just tested main and the latest release and for both setups I get the same failure.
