### ISSUE TITLE
Running on hardware partitions at TII

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [qiboteam/qibo-client#71]
I am not completely sure whether this is supported yet or not, nor if we intend to support it, but, in principle, by changing the `device` of the `Client`, will I be able to run on a quantum chip with `qibolab`?
Namely, if for instance I try to connect to the `qw11q` partition, which should be connected to the homonymous chip
``` python
from qibo import gates
import qibo_client

c = Circuit(11)
c.add(gates.GPI2(10, 0.)
c.add(gates.GPI2(10, 0.)
c.add(gates.M(10))

token = "xxxxx"
client = qibo_client.Client(token)

job = client.run_circuit(circuit, nshots=100, device="qw11q")
result = job.result()
print(result)
```
is it going to run on the chip? Because, by doing some testing it looks like it is just simulating on the partition.

**Comment by scarrazza** [comment]
Yes, it is possible, however yesterday we found a bug and in the next days @marcorossi5 will upload the fix to the frontend and backend.
