### ISSUE TITLE
`No such file or directory: result.npy` when running `CZ` on `etna` (aka qw11q)

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [qiboteam/qibo-client#75]
Trying to run a `CZ` between two connected qubits on `etna` (according to the platform info available [here](https://github.com/qiboteam/qibolab_platforms_qrc/tree/platform_readme/qw11q) ) :

``` python
from qibo import Circuit, gates
import qibo_client
 
# create the circuit you want to run
q = [10, 9]

c = Circuit(17)

c.add(gates.CZ(q[0],q[1]))
print(f"> Trying CZ on qubits {q}.")
# M
mes = c.add(gates.M(*q))
# authenticate to server through the client instance
token = "xxxx"
client = qibo_client.Client(token)
# run the circuit
job = client.run_circuit(c, nshots=1000, device="etna")
result = job.result()
print(result)
```
results in an error 
``` python
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qibo_client/fe8d66e71307434aafd9d70eac83d8b8/results.npy'
```

You actually get the same error, when trying out two disconnected qubits, e.g. `[10, 11]`.

**Comment by BrunoLiegiBastonLiegi** [comment]
Broadly speaking these crashes are a bit mysterious and hard to decipher, it would be better to catch the exception raised on the node and return it to the user, as also mentioned in #72.

**Comment by scarrazza** [comment]
I fully agree, I believe the job object should store the output (including stderr) and print it on demand or when the job crashes (as in this case).
