### ISSUE TITLE
Jobs not showing up at `https://cloud.qibo.science`

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [qiboteam/qibo-client#78]
The jobs I send never show up on the dashboard [https://cloud.qibo.science](https://cloud.qibo.science). Neither the queued jobs, nor the finished one are shown.
I presume the `Your jobs status` section should display them

![immagine](https://github.com/user-attachments/assets/55ebb950-f2a1-482f-bb5d-61c6d86e301e)

**Comment by BrunoLiegiBastonLiegi** [comment]
So sorry, I was apparently using an old API key (not sure where it did come from actually...), using the one reported on the dashboard worked fine. We can close.

**Comment by scarrazza** [comment]
Thanks for checking!
