### ISSUE TITLE
Improve runtime errors readability

### ISSUE THREAD

**Issue by marcorossi5** [qiboteam/qibo-client#79]
At the moment, when client crashes it's a python error.

The average user might not want it. Maybe create custom exception with some cosmetics.

**Comment by BrunoLiegiBastonLiegi** [comment]
I am not completely sure I completely got what's the plan for this. What do you mean exactly by improving the readability?
This is separated from  #72 and #75, right?

**Comment by marcorossi5** [comment]
> This is separated from #72 and #75, right?

Yes and no. Those two issues are linked to the daemon. I'm addressing them after daemon is ready. After that, no error should be raised by the client.

However, we should keep track of the cases when the client crashes (still I can't figure out) and handle all of them with a custom exception instead of raising an error.

**Comment by BrunoLiegiBastonLiegi** [comment]
Now that #83 has been merged I can probably go back to this. So, should I create a 
``` python
class JobFailure(Exception):
    ...
```
to be raised when the result of the execution on the server is not received? I am not completely sure about what happens right now when the job fails, do you receive `None` with a `200` response?

**Comment by marcorossi5** [comment]
This is what happens when the job fails:

https://github.com/qiboteam/qibo-client/blob/8e90f73663b3027d497a04083f1424dcc592ef73/src/qibo_client/qibo_job.py#L166-L179

The `job_status` equals `QiboJobStatus.ERROR`. This is retrieved by a call at this url: https://github.com/qiboteam/qibo-client/blob/8e90f73663b3027d497a04083f1424dcc592ef73/src/qibo_client/qibo_job.py#L207C9-L207C57

**Comment by marcorossi5** [comment]
When the qibo client crashes, we don't want the terminal output to contain all the error stack trace.
Refactor the custom exception to just extract the relevant piece of information and discard the rest.
Check out the `raise` in https://github.com/qiboteam/qibo-client/blob/main/src/qibo_client/utils.py
